
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - PrefixPath=/api/v1
        - CircuitBreaker=myCircuitBreaker
      routes:
        - id: shopping_cart_circuitbreaker_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
        - id: shopping-store_circuitbreaker_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                methods: GET, POST
                exceptions: ru.yandex.practicum.commerce.interaction.api.exception.NotFoundResource
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
        - id: delivery_circuitbreaker_route
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
        - id: order_circuitbreaker_route
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: payment_circuitbreaker_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
        - id: warehouse_circuitbreaker_route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true

server:
  port: 8080