spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

#  cloud:
#    openfeign:
#      circuitbreaker:
#        enabled: true
#        "request-service":
#          enabled: true

  datasource:
    driverClassName: "org.postgresql.Driver"
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:8032/main}
    username: ${SPRING_DATASOURCE_USERNAME:main}
    password: ${SPRING_DATASOURCE_PASSWORD:main}

#resilience4j:
#  circuitbreaker:
#    instances:
#      request-service:
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10000
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowType: COUNT_BASED
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: info

server:
  port: 0

stats-client:
  id: stats-server
